<testsuite errors="3" failures="1" name="searchTheHive.Search the hive" skipped="0" tests="4" time="1.231319"><testcase classname="searchTheHive.Search the hive" name="Brandon searches nectr" status="failed" time="0.645585"><error message="Message: Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//django%3A80..." type="WebDriverException">
<![CDATA[
Failing step: Given Brandon is on search the hive page ... failed in 0.521s
Location: features/searchTheHive.feature:24
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features/steps/searchTheHive.py", line 63, in step_impl
    context.driver.get(context.server_url + "/search/")
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//django%3A8000/search/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20django.
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'df2e6b0362a3', ip: '172.18.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.57-boot2docker', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.kJZKYFYotvCZ, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0.2, platformVersion=4.4.57-boot2docker, moz:processID=5536, browserName=firefox, platformName=linux}]
Session ID: 4c563e24-bd90-4232-a855-c28cec142e8c
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor15.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:133)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:99)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:43)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:604)
    at org.openqa.selenium.remote.RemoteWebDriver.get (RemoteWebDriver.java:325)
    at sun.reflect.GeneratedMethodAccessor25.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:104)
    at com.sun.proxy.$Proxy6.get (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.get (EventFiringWebDriver.java:163)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeUrl.java:40)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeUrl.java:25)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Brandon searches nectr
    Given Brandon is a registered user ... passed in 0.014s
    Given Mike is a registered user ... passed in 0.011s
    And Mike is signed into nectr ... passed in 0.099s
    Given Brandon is on search the hive page ... failed in 0.521s
    When Brandon types "Computer Science" in search box ... skipped in 0.000s
    And clicks search the hive button ... skipped in 0.000s
    And he can view preview of tutor profile ... skipped in 0.000s
    And he will see a view profile button ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="searchTheHive.Search the hive" name="Mike searches nectr" status="failed" time="0.467775"><error message="Message: Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//django%3A80..." type="WebDriverException">
<![CDATA[
Failing step: Given mike is on search the hive page ... failed in 0.352s
Location: features/searchTheHive.feature:33
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features/steps/searchTheHive.py", line 63, in step_impl
    context.driver.get(context.server_url + "/search/")
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//django%3A8000/search/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20django.
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'df2e6b0362a3', ip: '172.18.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.57-boot2docker', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.kJZKYFYotvCZ, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0.2, platformVersion=4.4.57-boot2docker, moz:processID=5536, browserName=firefox, platformName=linux}]
Session ID: 4c563e24-bd90-4232-a855-c28cec142e8c
Screenshot: available via screen
Stacktrace:
    at sun.reflect.GeneratedConstructorAccessor15.newInstance (None:-1)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:423)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException (W3CHttpResponseCodec.java:133)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:99)
    at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode (W3CHttpResponseCodec.java:43)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute (HttpCommandExecutor.java:163)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:604)
    at org.openqa.selenium.remote.RemoteWebDriver.get (RemoteWebDriver.java:325)
    at sun.reflect.GeneratedMethodAccessor25.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:104)
    at com.sun.proxy.$Proxy6.get (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.get (EventFiringWebDriver.java:163)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeUrl.java:40)
    at org.openqa.selenium.remote.server.handler.ChangeUrl.call (ChangeUrl.java:25)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Mike searches nectr
    Given Brandon is a registered user ... passed in 0.007s
    Given Mike is a registered user ... passed in 0.094s
    And Mike is signed into nectr ... passed in 0.014s
    Given mike is on search the hive page ... failed in 0.352s
    When mike types in what he is looking for in search box ... skipped in 0.000s
    And clicks search the hive button ... skipped in 0.000s
    And he can view preview of tutor profile ... skipped in 0.000s
    And he will see a view profile button ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="searchTheHive.Search the hive" name="Billy searches nectr for math tutors" status="failed" time="0.078126"><error message="value too long for type character varying(10)&#10;" type="DataError">
<![CDATA[
Failing step: Given there are 15 Math tutors ... failed in 0.055s
Location: features/searchTheHive.feature:50
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
nectr.courses.models.DoesNotExist: Courses matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(10)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features/steps/searchTheHive.py", line 118, in step_impl
    TutorFactory.create_batch(size=15)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 635, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 635, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 622, in create
    attrs = cls.attributes(create=True, extra=kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 453, in attributes
    force_sequence=force_sequence,
  File "/usr/local/lib/python3.5/site-packages/factory/containers.py", line 324, in build
    return stub.__fill__()
  File "/usr/local/lib/python3.5/site-packages/factory/containers.py", line 83, in __fill__
    res[attr] = getattr(self, attr)
  File "/usr/local/lib/python3.5/site-packages/factory/containers.py", line 108, in __getattr__
    val = val.evaluate(self, self.__containers)
  File "/usr/local/lib/python3.5/site-packages/factory/containers.py", line 227, in evaluate
    containers=containers,
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 324, in evaluate
    return self.generate(sequence, obj, create, defaults)
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 412, in generate
    return subfactory.simple_generate(create, **params)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 709, in simple_generate
    return cls.generate(strategy, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 676, in generate
    return action(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 623, in create
    return cls._generate(True, attrs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 548, in _generate
    obj = cls._prepare(create, **attrs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 523, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/django.py", line 179, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/django.py", line 170, in _get_or_create
    obj, _created = manager.get_or_create(*args, **key_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 475, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 505, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(10)

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Billy searches nectr for math tutors
    Given Brandon is a registered user ... passed in 0.006s
    Given Mike is a registered user ... passed in 0.005s
    And Mike is signed into nectr ... passed in 0.012s
    Given there are 15 Math tutors ... failed in 0.055s
    Given Billy is signed into nectr ... skipped in 0.000s
    And Billy is on search the hive page ... skipped in 0.000s
    When Billy clicks on search bar ... skipped in 0.000s
    And Billy enters "Math" ... skipped in 0.000s
    And Billy clicks "Submit" button ... skipped in 0.000s
    Then search results are loaded on search the hive page ... skipped in 0.000s
    And 10 tutor search results are displayed ... skipped in 0.000s
    And each search result contains "view tutor profile" button ... skipped in 0.000s
    When Billy clicks "more results" button ... skipped in 0.000s
    Then remaining 5 tutors are diaplyed ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="searchTheHive.Search the hive" name="Billy searches nectr for C++ programming tutors" status="failed" time="0.039832"><failure message="" type="AssertionError">
<![CDATA[
Failing step: Given there are 5 Cpp Programming tutors ... failed in 0.001s
Location: features/searchTheHive.feature:64
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features/steps/searchTheHive.py", line 239, in step_impl
    assert False
AssertionError
]]>
</failure><system-out>
<![CDATA[
@scenario.begin
  Scenario: Billy searches nectr for C++ programming tutors
    Given Brandon is a registered user ... passed in 0.007s
    Given Mike is a registered user ... passed in 0.005s
    And Mike is signed into nectr ... passed in 0.027s
    Given there are 5 Cpp Programming tutors ... failed in 0.001s
    Given Billy is signed into nectr ... skipped in 0.000s
    And Billy is on search the hive page ... skipped in 0.000s
    When Billy clicks on search bar ... skipped in 0.000s
    And Billy enters "Cpp Programming" ... skipped in 0.000s
    And Billy clicks "Submit" button ... skipped in 0.000s
    Then search results are loaded on search the hive page ... skipped in 0.000s
    And 5 tutor search results are displayed ... skipped in 0.000s
    And each search result contains "view tutor profile" button ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>